### ISSUE TITLE
Will it Work ?

### ISSUE THREAD

**Issue by CREVIOS** [KarthikRIyer/swiftplot#101]
Can i add the polar and piechart in following way :

Swift for TensorFlow includes python interoperability.
```python
let np = Python.import("numpy")
let plt = Python.import("matplotlib.pyplot")

let time = np.arange(0, 10, 0.01)
let amplitude = np.exp(-0.1 * time)
let position = amplitude * np.sin(3 * time)

plt.figure(figsize: [15, 10])

plt.plot(time, position)
plt.plot(time, amplitude)
plt.plot(time, -amplitude)

plt.xlabel("Time (s)")
plt.ylabel("Position (m)")
plt.title("Oscillations")
plt.show()
```
<b>plt.polar and plt.pie should just work.</b>

**Comment by CREVIOS** [comment]
I want to do it For GCI .

**Comment by boronhub** [comment]
Hi there! I don't think we are looking for solutions using Python interop, so please try implementing solutions in Swift using one of the three renderers. Best of luck!

**Comment by areebg9** [comment]
Hey! I recommend checking this out in the Issue with the GCI task - if you see, it looks like these two tasks (polar and pie chart) are already being done by other competitors, so I recommend you ask @KarthikRIyer if there are any other tasks to do.

**Comment by boronhub** [comment]
@CREVIOS you can do the stacked line chart task, I was planning on submitting a PR but since I have already completed another GCI task, you can do that one.

**Comment by WilliamHYZhang** [comment]
Good luck @CREVIOS! Let us know if you need any help.

**Comment by KarthikRIyer** [comment]
@CREVIOS the aim of these tasks is to implement plot types in in this library using just swift. We do not want to use python at all. The motive of the library is that anyone should be abke to plot graphs by providing the data. We do not want to use matplotlib to draw the graph. SwiftPlot is a library like matplotlib buy in Swift.
Polar and pie chart have already been claimed so of you want to work on anything else let me know.
