### ISSUE TITLE
Using SVGRenderer and QuartzRenderer

### ISSUE THREAD

**Issue by areebg9** [KarthikRIyer/swiftplot#103]
Hi! I tried to use SVGRenderer and QuartzRenderer, but I keep on getting this error:

```swift
error: <Cell 13>:2:19: error: use of undeclared type 'SVGRenderer'
var svg_renderer: SVGRenderer = SVGRenderer()
                  ^

<Cell 13>:2:19: note: cannot use module 'SVGRenderer' as a type
var svg_renderer: SVGRenderer = SVGRenderer()
```

My code is here:

```swift
import SVGRenderer
var svg_renderer: SVGRenderer = SVGRenderer()
```

The same happens with `QuartzRenderer`. How can I fix this?

**Comment by KarthikRIyer** [comment]
@Qwerty71 if you want to use SVGRenderer you need to compile it's module while including the library. Similiar to how you write AGGRenderer at the end of the %install statement.
`%install '.package(url: "https://github.com/KarthikRIyer/swiftplot", .branch("master"))' SwiftPlot AGGRenderer SVGRenderer QuartzRenderer`

But QuartzRenderer probably won't work with jupyter. It's available only on macOS, iOS , watchOS and tvOS platforms.

**Comment by anigasan** [comment]
@KarthikRIyer - I was getting same error for SVGRenderer even after adding to %install statement.

**Comment by Qwerty71** [comment]
Hey @anigasan , I ran it with the %install and it worked.

When I installed SwiftPlot, I ran this: 

```swift
%install '.package(url: "https://github.com/Qwerty71/swiftplot", .branch("polarChart"))' SwiftPlot SVGRenderer
```

**Comment by anigasan** [comment]
My bad, I was typing SGGRenderer in my import!! When I corrected it, it started working!

**Comment by KarthikRIyer** [comment]
No worries :D @anigasan
