### ISSUE TITLE
A Code Typo in README.md

### ISSUE THREAD

**Issue by keefo** [KarthikRIyer/swiftplot#135]
subPlot.drawGraphAndOutput(fileName: "subPlotsHorizontallyStacked", renderer: agg_renderer)

Should be

subplot.drawGraphAndOutput(fileName: "subPlotsHorizontallyStacked", renderer: agg_renderer)

**Comment by KarthikRIyer** [comment]
Thanks for reporting this @keefo !

Would you like to create a PR to fix this?

**Comment by keefo** [comment]
#136
