### ISSUE TITLE
AGG code currently doesn't compile on Mac

### ISSUE THREAD

**Issue by BradLarson** [KarthikRIyer/swiftplot#26]
I just pulled down the project to try to build on my Mac, and with the project as it is it throws errors about the right angle brackets in some of AGG's code. This looks like it's using the wrong C++ version by default:

https://stackoverflow.com/questions/8303955/clang-c11-invocation

so I believe that by changing the lines at the end of Package.swift to read

```
    ],
    cxxLanguageStandard: .cxx11
)
```

that should fix it. It solved these build errors on my Mac, and the whole project ran just fine there. I'd submit this as a pull request, but I wanted to make sure this worked on your end, as well. I can also verify on my Ubuntu workstation tomorrow.

**Comment by KarthikRIyer** [comment]
@BradLarson it works on my end.
