### ISSUE TITLE
Create New Function for Coordinate Conversion

### ISSUE THREAD

**Issue by WilliamHYZhang** [KarthikRIyer/swiftplot#76]
It would be beneficial to have a function that simply converts coordinate points to absolute points on the image, and use that function for all the annotations and other applications that will eventually use them.

From @KarthikRIyer:
> Yes I suppose you could generalize this conversion. You would always need the output to be in image space so you could have a function that takes in a point, the plot dimensions the input coordinate system and returns the point in the specified output coordinate system.
If this function is to be used by the plots too then it would be better to put it under HelperFunctions.
It would be better to discuss this with others before moving forward. @odmir @karwa?

I hope that I'll be able to work on implementing this soon once the idea is ironed out.

**Comment by WilliamHYZhang** [comment]
Currently, I'm planning on writing out the function in ```HelperFunctions``` and rolling it to only the annotations at first. Later, we can see if the other files would benefit from this as well.

**Comment by KarthikRIyer** [comment]
@WilliamHYZhang you can move forward with writing the function. We'll definitely need it for the annotations. We can decide later if we should replace it in the Plots. Create an overload for the functions to use just one point or an array of points. If we want to use it for plots, we don't wan't a large number of function invocations in case there are many points to process.

**Comment by karwa** [comment]
The thing about a helper function is that we don't actually know where the plot will be until we lay it all out; and depends on things like whether you have axis labels on/off. We actually have several useful coordinate systems. For example, matplotlib defines 9 of them:

```
'figure points'   : points from the lower left corner of the figure
'figure pixels'   : pixels from the lower left corner of the figure
'figure fraction' : 0,0 is lower left of figure and 1,1 is upper, right
'axes points'     : points from lower left corner of axes
'axes pixels'     : pixels from lower left corner of axes
'axes fraction'   : 0,0 is lower left of axes and 1,1 is upper right
'offset points'   : Specify an offset (in points) from the xy value
'offset pixels'   : Specify an offset (in pixels) from the xy value
'data'            : use the axes data coordinate system
```
From: https://matplotlib.org/gallery/text_labels_and_annotations/annotation_demo.html#specifying-text-points-and-annotation-points

I think it might make sense for us to define a `CoordinateSpace` enum with similar coordinate spaces, and a `Coordinate` type which holds a `Point` and `CoordinateSpace`. Then the `GraphLayout` would resolve these in to absolute positions and offsets for the renderer.

**Comment by WilliamHYZhang** [comment]
Thanks for the comments, will work on implementation. :+1:

**Comment by WilliamHYZhang** [comment]
Ok, so instead of taking in a `Point` as the `location` argument, we would take a `Coordinate` instead. We than make the `draw` function have an additional argument, `point`, which will be passed through `GraphLayout` after it resolves the `Coordinate` into absolute positions.

**Comment by WilliamHYZhang** [comment]
Actually, I think we can just overwrite the `location` in `GraphLayout`. Will add this as a requirement in the `Annotation` protocol.

EDIT: just realized that some annotations don't have` location`, for example arrow, which has `start` and `end` of type `Point`. Maybe we can change this `location` to an array of `Point`s instead, and `GraphLayout` will resolve all of them appropriately?

**Comment by WilliamHYZhang** [comment]
Please continue discussion at #88
