### ISSUE TITLE
Missing points, strange errors in line graph

### ISSUE THREAD

**Issue by WilliamHYZhang** [KarthikRIyer/swiftplot#81]
When plotting line graph, some points aren't being plotted. Came across this bug when working on ML with S4TF and using SwiftPlot to visualize accuracy. Note that the "train" series for epoch 1 is missing.

![image](https://user-images.githubusercontent.com/39932068/71692477-fb60ba80-2d77-11ea-87f5-9f8aee9f1b2c.png)

It has something to do with the y axis scaling, it's really acting quite strange.

Here's a small example for reproducibility:
```
let x:[Float] = [0, 1, 2, 3]
let y:[Float] = [70, 80, 95, 100]

var lineGraph = LineGraph<Float,Float>(enablePrimaryAxisGrid: true)
lineGraph.addSeries(x, y, label: "Plot 1", color: .lightBlue)
lineGraph.plotTitle.title = "SINGLE SERIES"
lineGraph.plotLabel.xLabel = "X-AXIS"
lineGraph.plotLabel.yLabel = "Y-AXIS"
lineGraph.plotLineThickness = 3.0

lineGraph.drawGraph(renderer: agg_renderer)
display(base64EncodedPNG: agg_renderer.base64Png())
```
Output (point missing!):
![image](https://user-images.githubusercontent.com/39932068/71694494-5c3ec180-2d7d-11ea-8d86-33e74b1386f3.png)

And when we just make a change to the first point:
```
let x:[Float] = [0, 1, 2, 3]
let y:[Float] = [0, 80, 95, 100]

var lineGraph = LineGraph<Float,Float>(enablePrimaryAxisGrid: true)
lineGraph.addSeries(x, y, label: "Plot 1", color: .lightBlue)
lineGraph.plotTitle.title = "SINGLE SERIES"
lineGraph.plotLabel.xLabel = "X-AXIS"
lineGraph.plotLabel.yLabel = "Y-AXIS"
lineGraph.plotLineThickness = 3.0

lineGraph.drawGraph(renderer: agg_renderer)
display(base64EncodedPNG: agg_renderer.base64Png())
```
Output (as expected):
![image](https://user-images.githubusercontent.com/39932068/71694604-a9229800-2d7d-11ea-9c57-7b36846b4670.png)

What is going on here?

**Comment by WilliamHYZhang** [comment]
Also, when dealing with decimals sometimes the graph doesn't show anything at all. For example, floats that are very close to each other in y-value.

**Comment by KarthikRIyer** [comment]
I'm not sure if @karwa's PR will fix this because it doesn't change the output in any way. Thank's for reporting this. I'll take a look as soon as I can.

**Comment by karwa** [comment]
Yes that PR doesn't fix this AFAIK.
